# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  node: circleci/node@1.0.1
  gke: circleci/gcp-gke@0.1.0
  kubernetes: circleci/kubernetes@0.11.2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: build app
          command: sleep 10
  unit-test:
    machine: true
    steps:
      - checkout
      - run:
          name: unit test
          command: sleep 10
  functional-test:
    machine: true
    steps:
      - checkout
      - run:
          name: functional test
          command: sleep 10
  create-update-deployment:
    machine: true
    steps:
      - checkout
      - gke/install
      - gke/init
      - gke/update-kubeconfig-with-credentials:
          cluster: cluster-1
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: app/api.yaml
          resource-name: deployment/api
          show-kubectl-command: true

workflows:
  build_and_deploy:
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - functional-test:
          requires:
            - build
      - create-update-deployment:
          requires:
            - unit-test
            - functional-test
