# Service to expose web frontend
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: metrics
spec:
  selector:
    group: api
  ports:
  - name: metrics
    protocol: TCP
    port: 9102
    targetPort: 9102

---
# API service version 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        group: api
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/service-meta-version": "v1"
        "consul.hashicorp.com/service-tags": "v1"
        #"consul.hashicorp.com/service-meta-version": "v2"
        #"consul.hashicorp.com/service-tags": "v2"
    spec:
      containers:
      - name: api
        image: nicholasjackson/fake-service:v0.20.0
        ports:
        - containerPort: 9090
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9090"
        - name: "NAME"
          value: "api-v1"
          #value: "api-v2"
        - name: "MESSAGE"
          value: "Response from API v1"
          #value: "Response from API v2"
          # - name: "ERROR_RATE"
          #   value: "0.5"
